#!/usr/bin/env bash
# Orchestrates the whole seed, from inside the bootstrap helper container on the
# compose network. Waits for both services, provisions credentials + seed data,
# and writes the discovered credentials to /out/.env.generated (mounted to
# integration/) for the host-side smoke run to consume.
set -euo pipefail

# Internal (compose-network) URLs the bootstrap talks to. These differ from the
# host-facing URLs the SmokeTests app uses -- the account/crypto is the same
# server either way, so the credentials are portable.
export VW_URL="http://vaultwarden"
export INF_URL="http://infisical:8080"
export VAULT_URL="http://vault:8200"
: "${BITWARDEN_MASTER_PASSWORD:?}"
# Seed map lives in seed.json (mounted at /out) rather than .env.
export SMOKE_SEED_JSON="$(cat /out/seed.json)"

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="/out/.env.generated"

wait_for() {
  local name="$1" url="$2" tries=60
  echo "[bootstrap] waiting for ${name} (${url})"
  until curl -fsS "$url" >/dev/null 2>&1; do
    tries=$((tries - 1)); [ "$tries" -le 0 ] && { echo "[bootstrap] ${name} never became ready"; exit 1; }
    sleep 3
  done
  echo "[bootstrap] ${name} ready"
}

wait_for "VaultWarden" "${VW_URL}/alive"
wait_for "Infisical"   "${INF_URL}/api/status"
wait_for "Vault"       "${VAULT_URL}/v1/sys/health"

echo "[bootstrap] === VaultWarden ==="
vw_json="$(node "${HERE}/vaultwarden-register.mjs")"
BW_CLIENT_ID="$(jq -r '.clientId' <<<"$vw_json")"
BW_CLIENT_SECRET="$(jq -r '.clientSecret' <<<"$vw_json")"

echo "[bootstrap] === Infisical ==="
inf_json="$(bash "${HERE}/seed-infisical.sh")"
INF_CLIENT_ID="$(jq -r '.clientId' <<<"$inf_json")"
INF_CLIENT_SECRET="$(jq -r '.clientSecret' <<<"$inf_json")"
INF_PROJECT_ID="$(jq -r '.projectId' <<<"$inf_json")"

# Write the discovered credentials now, before the (credential-free) Vault seed,
# so a Vault hiccup can't leave a stale .env.generated behind.
echo "[bootstrap] writing ${OUT}"
cat > "$OUT" <<EOF
# Generated by integration/bootstrap on the last \`docker compose run --rm bootstrap\`.
# Discovered credentials only; static config stays in .env. Git-ignored.
BITWARDEN_CLIENT_ID=${BW_CLIENT_ID}
BITWARDEN_CLIENT_SECRET=${BW_CLIENT_SECRET}
INFISICAL_CLIENT_ID=${INF_CLIENT_ID}
INFISICAL_CLIENT_SECRET=${INF_CLIENT_SECRET}
INFISICAL_PROJECT_ID=${INF_PROJECT_ID}
EOF

echo "[bootstrap] === Vault ==="
# Vault dev-mode credentials are static (known root token), so nothing is
# discovered here -- just seed the data. Config lives in .env.
bash "${HERE}/seed-vault.sh"

echo "[bootstrap] done. Run ./run-smoke.sh from the host."
